### ISSUE TITLE
Settings::get() does not work

### ISSUE THREAD

**Issue by zuernBernhard** [BurdaMagazinOrg/module-shariff-backend#3]
At the moment the modules config is not used :

`$backend_settings = Settings::get('shariff_backend');` 

https://github.com/BurdaMagazinOrg/module-shariff-backend/blob/8.x-1.x/src/ShariffBackend.php#L57

--> $backend_settings is null after that.

![screen](https://cloud.githubusercontent.com/assets/1442798/20216112/fe6272b0-a818-11e6-87ec-ecd1de74859a.png)

**Comment by mxhCodes** [comment]
Merged and available now in alpha4.
