### ISSUE TITLE
Outdated heise/shariff

### ISSUE THREAD

**Issue by pagachdrunomics** [BurdaMagazinOrg/module-shariff-backend#8]
Request are resulting in `426 Unknown` response: Upgrade Required. 
heise/shariff should be updated to latest 7.x version to keep the same php requirements

**Comment by AndreBaumeier** [comment]
8.x seems to be available already? can you test the existing PR https://github.com/BurdaMagazinOrg/module-shariff-backend/pull/9 and respond if it works? Ill go ahead and merge it afterwards.

**Comment by AndreBaumeier** [comment]
just merged it. feel free to comment if something is missing.

**Comment by pagachdrunomics** [comment]
Can you tag a new release pls?
